FROM ubuntu:20.04

ENV PYTHONUNBUFFERED=1

EXPOSE 5001

RUN apt-get update
RUN apt-get install -y python3 python3-pip
RUN apt-get install -y git
RUN apt-get install -y libssl-dev 
RUN ln -snf /usr/share/zoneinfo/$CONTAINER_TIMEZONE /etc/localtime && echo $CONTAINER_TIMEZONE > /etc/timezone

RUN mkdir -p /home/application
COPY requirements.txt /home/application
WORKDIR /home/application

# RUN pip3 install --upgrade pip
RUN set -ex
RUN pip3 install -r requirements.txt
RUN pip3 uninstall -y pyopenssl
RUN pip3 install -U pyopenssl
RUN pip3 install aioquic
RUN pip3 install flask==2.1.3
RUN pip3 install werkzeug==2.0.3
RUN export LC_ALL=C.UTF-8
RUN export LANG=C.UTF-8

COPY . .

WORKDIR /home/application/Quic/receiver
RUN ls
CMD ["python3", "server.py", "--certificate", "ssl_cert.pem", "--private-key", "ssl_key.pem"]