FROM ubuntu:20.04

ENV PYTHONUNBUFFERED=1

EXPOSE 8000

RUN apt-get update
RUN apt-get install -y python3 python3-pip
RUN ln -snf /usr/share/zoneinfo/$CONTAINER_TIMEZONE /etc/localtime && echo $CONTAINER_TIMEZONE > /etc/timezone